import { query } from './db.js';

export async function seedInteraktCampaignSamples() {
  console.log('[PostgreSQL] Seeding 14 exact Interakt-replica campaign sample ideas...');

  const interaktSamples = [
    {
      id: 'tmpl_sample_01',
      name: 'Promotional Offer 01',
      category: 'MARKETING',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Offers',
      is_sample: true,
      header_type: 'NONE',
      header_text: 'Exciting Offers Just for You!',
      body_text: '🎉 Enjoy exclusive offers at ARCO!\nGet the best experiences with our services. Don\'t miss out!\n\nBook now to avail these deals! 🚀\n\nFor more details, click below:\n📞 Contact us: +919920858396',
      footer_text: 'Reply STOP to opt-out',
      buttons: JSON.stringify([
        { type: 'URL', text: 'View More', url: 'https://arcocommunication.com/deals' },
        { type: 'QUICK_REPLY', text: 'STOP' },
      ]),
      sample_variables: JSON.stringify([]),
    },
    {
      id: 'tmpl_sample_02',
      name: 'Transactional Confirmation 02',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Booking',
      is_sample: true,
      header_type: 'NONE',
      header_text: 'Order Confirmed',
      body_text: 'Your order with ARCO has been confirmed!\n\nOrder Details:\n- Order ID: {{1}}\n- Delivery Date: {{2}}\n- Amount Paid: {{3}}',
      footer_text: 'Thank you for choosing ARCO',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Track Order', url: 'https://arcocommunication.com/orders' },
        { type: 'PHONE_NUMBER', text: 'Customer Support', phone_number: '+919876543210' },
      ]),
      sample_variables: JSON.stringify(['ORD-9821', 'Tomorrow by 6 PM', '₹1,499.00']),
    },
    {
      id: 'tmpl_sample_03',
      name: 'Service Alert 03',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Alerts',
      is_sample: true,
      header_type: 'TEXT',
      header_text: 'System Service Notice',
      body_text: 'Dear {{1}}, our technical team will be performing scheduled maintenance on {{2}} between {{3}} and {{4}}. Services will continue with minimal disruption.',
      footer_text: 'ARCO Engineering Operations',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Status Page', url: 'https://status.arcocommunication.com' },
      ]),
      sample_variables: JSON.stringify(['Valued Customer', 'Sunday, Aug 24', '02:00 AM', '04:00 AM']),
    },
    {
      id: 'tmpl_sample_04',
      name: 'Lead Qualification 04',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Leads',
      is_sample: true,
      header_type: 'TEXT',
      header_text: 'Quick Inquiry Follow-up',
      body_text: 'Hi {{1}}, thanks for showing interest in ARCO WhatsApp Commerce! Which feature are you most excited to explore for your business?',
      footer_text: 'Select an option below',
      buttons: JSON.stringify([
        { type: 'QUICK_REPLY', text: 'Catalog & Checkout' },
        { type: 'QUICK_REPLY', text: 'Broadcast Campaigns' },
        { type: 'QUICK_REPLY', text: 'Chatbot Automation' },
      ]),
      sample_variables: JSON.stringify(['Priya']),
    },
    {
      id: 'tmpl_sample_05',
      name: 'Informative Update 05',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Updates',
      is_sample: true,
      header_type: 'NONE',
      header_text: 'Platform Feature Update',
      body_text: 'Hello {{1}}, we have released new platform updates for your workspace. You can now track live read rates and click conversions in real time.',
      footer_text: 'ARCO Product Updates',
      buttons: JSON.stringify([
        { type: 'URL', text: 'See What\'s New', url: 'https://arcocommunication.com/changelog' },
      ]),
      sample_variables: JSON.stringify(['Amit']),
    },
    {
      id: 'tmpl_sample_06',
      name: 'Occasion Special 06',
      category: 'MARKETING',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Special',
      is_sample: true,
      header_type: 'TEXT',
      header_text: '🎉 Celebrate with Exclusive Savings!',
      body_text: 'Hi {{1}},\n\nTo make this celebration extra special, we\'re offering a flat 30% discount on all premium services. Use promo code CELEBRATE30 at checkout.',
      footer_text: 'Valid till midnight tonight',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Claim Special Offer', url: 'https://arcocommunication.com/celebrate' },
        { type: 'QUICK_REPLY', text: 'Remind Me Later' },
      ]),
      sample_variables: JSON.stringify(['Rohan']),
    },
    {
      id: 'tmpl_sample_07',
      name: 'Promotional Discount 07',
      category: 'MARKETING',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Promo',
      is_sample: true,
      header_type: 'NONE',
      header_text: 'Special Discount Offer',
      body_text: '🎉 We appreciate your loyalty!\n\nEnjoy a special discount of {{1}}% off on your next purchase with code {{2}}. Don\'t miss out on this opportunity!\n\nShop now!',
      footer_text: 'Valid for 48 hours only',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Claim Discount', url: 'https://arcocommunication.com/shop' },
      ]),
      sample_variables: JSON.stringify(['25', 'FESTIVE25']),
    },
    {
      id: 'tmpl_sample_08',
      name: 'Service Alert 08',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Alerts',
      is_sample: true,
      header_type: 'NONE',
      header_text: 'Security Alert Notice',
      body_text: 'Security Alert: A new login was detected for your account {{1}} from IP {{2}} on {{3}}. If this was not you, please secure your account immediately.',
      footer_text: 'ARCO Security Operations Center',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Secure Account', url: 'https://arcocommunication.com/security' },
      ]),
      sample_variables: JSON.stringify(['user@company.com', '103.21.244.2', 'Today at 04:15 PM']),
    },
    {
      id: 'tmpl_sample_09',
      name: 'Informative Tips 09',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Tips',
      is_sample: true,
      header_type: 'TEXT',
      header_text: 'Pro Tip: Boost WhatsApp Conversions',
      body_text: 'Hi {{1}}, did you know that personalized broadcasts achieve 3x higher response rates? Use dynamic custom attributes in your next campaign.',
      footer_text: 'ARCO Growth Insights',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Read Guide', url: 'https://arcocommunication.com/resources' },
      ]),
      sample_variables: JSON.stringify(['Neha']),
    },
    {
      id: 'tmpl_sample_10',
      name: 'Lead Qualification 10',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Leads',
      is_sample: true,
      header_type: 'NONE',
      header_text: 'Enterprise Demo Confirmation',
      body_text: 'Hi {{1}}, we received your enterprise demo request for {{2}}. Our solution architect is ready to assist you. When is the best time for a quick 15-min call?',
      footer_text: 'ARCO Sales Team',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Book Demo Slot', url: 'https://arcocommunication.com/calendar' },
        { type: 'QUICK_REPLY', text: 'Call Me Today' },
      ]),
      sample_variables: JSON.stringify(['Vikram', '10,000+ Monthly Messages']),
    },
    {
      id: 'tmpl_sample_11',
      name: 'Occasion Reminder 11',
      category: 'MARKETING',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Festival',
      is_sample: true,
      header_type: 'TEXT',
      header_text: '✨ Wishing You a Happy Diwali!',
      body_text: 'Dear {{1}}, may this festive season bring prosperity and joy to you and your family! Celebrate with our festive gift hamper.',
      footer_text: 'Festive Greetings from ARCO',
      buttons: JSON.stringify([
        { type: 'URL', text: 'View Gift Hampers', url: 'https://arcocommunication.com/festive' },
      ]),
      sample_variables: JSON.stringify(['Deepak']),
    },
    {
      id: 'tmpl_sample_12',
      name: 'Promotional Event 12',
      category: 'MARKETING',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Events',
      is_sample: true,
      header_type: 'TEXT',
      header_text: '🌟 Special Invitation Inside',
      body_text: 'Hi {{1}},\n\nYou are cordially invited to our exclusive customer summit on {{2}} at {{3}}.\nReserve your VIP pass today!',
      footer_text: 'Limited seats available',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Reserve VIP Pass', url: 'https://arcocommunication.com/summit' },
      ]),
      sample_variables: JSON.stringify(['Ananya', 'Friday, Nov 14', 'ITC Grand Chola, Chennai']),
    },
    {
      id: 'tmpl_sample_13',
      name: 'Informative Service 13',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Services',
      is_sample: true,
      header_type: 'NONE',
      header_text: 'Monthly Invoice Available',
      body_text: 'Hello {{1}}, your monthly subscription invoice #{{2}} for the amount {{3}} is ready for download.',
      footer_text: 'ARCO Billing',
      buttons: JSON.stringify([
        { type: 'URL', text: 'Download PDF', url: 'https://arcocommunication.com/invoices' },
      ]),
      sample_variables: JSON.stringify(['Suresh', 'INV-2026-08', '₹4,999.00']),
    },
    {
      id: 'tmpl_sample_14',
      name: 'Transactional Ticket 14',
      category: 'UTILITY',
      language: 'en_US',
      status: 'APPROVED',
      theme: 'Support',
      is_sample: true,
      header_type: 'TEXT',
      header_text: 'Support Ticket Update',
      body_text: 'Hi {{1}}, your support ticket #{{2}} regarding "{{3}}" has been marked as RESOLVED by our engineering team.',
      footer_text: 'ARCO Customer Care',
      buttons: JSON.stringify([
        { type: 'QUICK_REPLY', text: 'Reopen Ticket' },
        { type: 'QUICK_REPLY', text: 'Rate Support 5★' },
      ]),
      sample_variables: JSON.stringify(['Kavita', 'TCK-8819', 'Webhook delivery latency']),
    },
  ];

  for (const t of interaktSamples) {
    await query(
      `INSERT INTO campaign_templates (
        id, name, category, language, status, theme, is_sample, header_type, header_text, body_text, footer_text, buttons, sample_variables
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        category = EXCLUDED.category,
        language = EXCLUDED.language,
        status = EXCLUDED.status,
        theme = EXCLUDED.theme,
        is_sample = EXCLUDED.is_sample,
        header_type = EXCLUDED.header_type,
        header_text = EXCLUDED.header_text,
        body_text = EXCLUDED.body_text,
        footer_text = EXCLUDED.footer_text,
        buttons = EXCLUDED.buttons,
        sample_variables = EXCLUDED.sample_variables,
        updated_at = CURRENT_TIMESTAMP`,
      [
        t.id,
        t.name,
        t.category,
        t.language,
        t.status,
        t.theme,
        t.is_sample,
        t.header_type,
        t.header_text,
        t.body_text,
        t.footer_text,
        t.buttons,
        t.sample_variables,
      ]
    );
  }

  console.log('[PostgreSQL] Successfully seeded 14 exact Interakt sample templates.');
}

if (process.argv[1]?.includes('seedInteraktCampaignSamples')) {
  seedInteraktCampaignSamples()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
